import type { Metadata } from "next";
import { Norican } from "next/font/google";
import "@/app/styles/globals.css";

const norican = Norican({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-norican'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased ${norican.variable}`}>
      <head>
        <script src="https://kit.fontawesome.com/22c21b90be.js" crossOrigin="anonymous"></script>
      </head>
      <body className="min-h-full flex flex-col justify-center items-center">{children}</body>
    </html>
  );
}
